AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless application for onboarding AWS account to Dome9
Metadata:
  AWS::ServerlessRepo::Application:
    Name: dome9-automatic-onboarding
    Description: Automatic onboarding flow triggered by account creation via ControlTower
    Author: SRE team
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://test-control-tower-integration/86d3f3a95c324c9479bd8986968f4327
    ReadmeUrl: s3://test-control-tower-integration/6835ce16ec75d83397ab732de4fa2faa
    Labels:
    - Dome9
    - automation
    - checkpoint
    HomePageUrl: https://github.com/dome9/serverless-aws-onboarding
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/dome9/serverless-aws-onboarding
Parameters:
  NotificationEmail:
    Type: String
  Dome9AccessId:
    Type: String
    Default: ACCESS_ID
  Dome9SecretKey:
    Type: String
    Default: SECRET_KEY
Resources:
  Dome9AutomationLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://test-control-tower-integration/0468f4631cd81e7c324b9ada3f2d5a5d
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 300
      Role:
        Fn::GetAtt:
        - Dome9AutomationLambdaRole
        - Arn
      Events:
        CWLifecycleEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
              - AWS Service Event via CloudTrail
              source:
              - aws.controltower
              detail:
                eventName:
                - CreateManagedAccount
      Tags:
        Name: CreateManagedAccountDome9Automation
      Environment:
        Variables:
          PRINCIPAL_ARN:
            Fn::GetAtt:
            - Dome9AutomationLambdaRole
            - Arn
          DOME9_ACCESS_ID:
            Ref: Dome9AccessId
          DOME9_SECRET_KEY:
            Ref: Dome9SecretKey
  Dome9AutomationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
          Condition: {}
      Path: /
      Policies:
      - PolicyName: Dome9OnboardingLambdaCloudformationAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: cloudformation:CreateStackInstances
            Resource: arn:aws:cloudformation:*:*:stackset/Dome9AutomaticOnboardingStackSet:*
          - Sid: VisualEditor1
            Effect: Allow
            Action: cloudformation:CreateStackSet
            Resource: '*'
          - Sid: VisualEditor2
            Effect: Allow
            Action: cloudformation:DeleteStackInstances
            Resource: arn:aws:cloudformation:*:*:stackset/Dome9AutomaticOnboardingStackSet:*
          - Sid: VisualEditor3
            Effect: Allow
            Action: cloudformation:DescribeStackSetOperation
            Resource: arn:aws:cloudformation:*:*:stackset/Dome9AutomaticOnboardingStackSet:*
      - PolicyName: PermitPassRoleOnAWSControlTowerStackSetRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action: iam:PassRole
            Resource: arn:aws:iam::*:role/service-role/AWSControlTowerStackSetRole
      - PolicyName: GetDome9ApiSecretPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:*:*:secret:Dome9ApiKeys-*
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  Dome9AutomationLambdaAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint:
          Ref: NotificationEmail
  CreateManagedAccountDome9AutomationLambdaAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: Dome9AutomationLambdaAlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: Dome9AutomationLambda
      EvaluationPeriods: 1
      MetricName: Errors
      TreatMissingData: notBreaching
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'
