AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless application for onboarding AWS account to Dome9

Parameters:
    NotificationEmail:
      Type: String

Resources:
  Dome9OnboardingPython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: Serverless application for onboarding AWS account to Dome9
      MemorySize: 128
      Timeout: 5

      Environment:
        Variables:
          DOME9_ACCESS_ID: <enter value here>
          DOME9_SECRET_KEY: <enter value here>

  CWEvent:
    Type: AWS::Events::Rule
    Properties:
      Input: '{"Key": "Value"}'
      Pattern:
        detail:
          state:
            - CreateManagedAccount

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: !Ref NotificationEmail

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref Dome9OnboardingPython3
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: '1'
